### ISSUE TITLE
Access violation from LSP when trying to make action (add/delete) with unit search path

### ISSUE THREAD

**Issue by Hunter200165** [coolchyni/fpctoolkit#2]
When trying to add or delete item to/from "Search Path" section of extension settings, LSP responds with `{"jsonrpc":"2.0","error":{"code":-32603,"message":"Access violation"},"id":null}`

It is extremely inconvenient, because LSP cannot get additional paths to search modules into and therefore constantly provide you with error, like `unit xyz not found`

![image](https://user-images.githubusercontent.com/37095578/188116758-75765ef6-916c-4db8-bb8f-fcf56fae1bf0.png)
^^ In this image I attempted to add new path (first Access Vioation response) and then remove path that already was there (second Access Violation).

As I know, this error is reproduced over several machines, because I recently tried installing extension on my laptop and it also ignores added paths.

Thank you for this great extension! :)

**Comment by Hunter200165** [comment]
Also tried to debug LSP using source code you have in repository (https://github.com/coolchyni/pascal-language-server), however your extension does not even start with exe compiled from it (it outputs something like `connection to server erroring, shutting server down` or something like that). 
I wanted to push binary file with debug information so I can attach lazarus debugger to pasls.exe process and see what is happening in the server and how it could be possibly solved.

**Comment by xuming** [comment]
Please try version 1.1.3, it's a very significant update.

**Comment by Hunter200165** [comment]
Sorry for a massive delay in response, have not written since then and now tried — actually, I think the update fixed the problem, so I guess the issue might be closed now.
Thank you again :)
